### ISSUE TITLE
problem starting a stopped instance

### ISSUE THREAD

**Issue by bowlby** [ployground/ploy#24]
Hi,
Thanks for updating mr.awsome, I was secretly hoping for that a long time.

I still have an issue when starting a stopped instance. I'm working on Mac OS X (Lion).

Below is my error. Anybody any idea?

kind regards!

INFO: Instance 'productie-2' available.
INFO: Instance state: stopped
INFO: Instance already started, waiting until it's available
Traceback (most recent call last):
  File "./bin/aws", line 18, in <module>
    mr.awsome.aws(configpath = "/Users/bowlby/Edubroker/newawsome/etc")
  File "/Users/bowlby/Edubroker/newawsome/eggs/mr.awsome-0.10-py2.7.egg/mr/awsome/__init__.py", line 451, in aws
    return aws(argv)
  File "/Users/bowlby/Edubroker/newawsome/eggs/mr.awsome-0.10-py2.7.egg/mr/awsome/__init__.py", line 445, in __call__
    args.func(sub_argv, args.func.__doc__)
  File "/Users/bowlby/Edubroker/newawsome/eggs/mr.awsome-0.10-py2.7.egg/mr/awsome/__init__.py", line 158, in cmd_start
    instance = server.start(overrides)
  File "/Users/bowlby/Edubroker/newawsome/eggs/mr.awsome-0.10-py2.7.egg/mr/awsome/ec2.py", line 212, in start
    log.error("Something went wrong, instance status: %s", instance.status)
AttributeError: 'Instance' object has no attribute 'status'

**Comment by fschulze** [comment]
Well, it's been a while. At some point it must have started working, not sure when. With current ploy_ec2 it works for me.
